### ISSUE TITLE
Update User Guide

### ISSUE THREAD

**Issue by huixuant** [AY2223S2-CS2103T-T13-3/tp#27]
Update user guide with features planned for v1.2:

* [x] Add feature (Xylus) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/21
* [x] Delete feature (Hui Xuan) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/22
* [x] Edit feature (Jiaxin) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/23
* [x] Help feature (Noah) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/25
* [x] List feature (Zhizhou) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/24
* [x] Find feature (Zhizhou) https://github.com/AY2223S2-CS2103T-T13-3/tp/issues/26
